
# CVE-2022-0718

| **Name** | CVE-2022-0718 |
| --- | --- |
| **Description** | A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( " ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext. |
| **Source** | [CVE](https://www.cve.org/CVERecord?id=CVE-2022-0718) (at [NVD](https://nvd.nist.gov/vuln/detail/CVE-2022-0718); [CERT](https://www.kb.cert.org/vuls/byid?searchview=&query=CVE-2022-0718), [LWN](https://lwn.net/Search/DoSearch?words=CVE-2022-0718), [oss-sec](https://marc.info/?l=oss-security&s=CVE-2022-0718), [fulldisc](https://marc.info/?l=full-disclosure&s=CVE-2022-0718), [Red Hat](https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2022-0718), [Ubuntu](https://people.canonical.com/~ubuntu-security/cve/CVE-2022-0718), [Gentoo](https://bugs.gentoo.org/show_bug.cgi?id=CVE-2022-0718), SUSE [bugzilla](https://bugzilla.suse.com/show_bug.cgi?id=CVE-2022-0718)/[CVE](https://www.suse.com/security/cve/CVE-2022-0718/), GitHub [advisories](https://github.com/advisories?query=CVE-2022-0718)/[code](https://github.com/search?type=Code&q=%22CVE-2022-0718%22)/[issues](https://github.com/search?type=Issues&q=%22CVE-2022-0718%22), [web search](https://duckduckgo.com/html?q=%22CVE-2022-0718%22), [more](https://oss-security.openwall.org/wiki/vendors)) |
| **References** | [DLA-3106-1](/tracker/DLA-3106-1) |

## Vulnerable and fixed packages

The table below lists information on source packages.

| Source Package | Release | Version | Status |
| --- | --- | --- | --- |
| [python-oslo.utils](/tracker/source-package/python-oslo.utils) ([PTS](https://tracker.debian.org/pkg/python-oslo.utils)) | bullseye | 4.6.0-2 | vulnerable |
|  | bullseye (security) | 4.6.1-0+deb11u1 | vulnerable |
|  | bookworm | 6.0.1-2 | fixed |
|  | sid, trixie | 7.3.0-4 | fixed |

The information below is based on the following data on fixed versions.

| Package | Type | Release | Fixed Version | Urgency | Origin | Debian Bugs |
| --- | --- | --- | --- | --- | --- | --- |
| [python-oslo.utils](/tracker/source-package/python-oslo.utils) | source | buster | 3.36.5-0+deb10u2 |  | [DLA-3106-1](/tracker/DLA-3106-1) |  |
| [python-oslo.utils](/tracker/source-package/python-oslo.utils) | source | (unstable) | 4.10.1-1 |  |  |  |

## Notes

```
[bullseye] - python-oslo.utils <no-dsa> (Minor issue)
<https://bugzilla.redhat.com/show_bug.cgi?id=2056850>
[https://bugs.launchpad.net/oslo.utils/+bug/1949623](https://bugs.launchpad.net/oslo.utils/%2Bbug/1949623)
Fixed by: <https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa> (4.12.1)
Fixed by: <https://opendev.org/openstack/oslo.utils/commit/5ce8a7f0f8ecec7a85a23ec3d7a7fb1cad14ceba> (4.10.1)

```

---

Search for package or bug name:  [Reporting problems](/tracker/data/report)

[Home](/tracker/) - [Debian Security](https://www.debian.org/security/) - [Source](https://salsa.debian.org/security-tracker-team/security-tracker/blob/master/bin/tracker_service.py) [(Git)](https://salsa.debian.org/security-tracker-team/security-tracker)

