{
  "cve_id": "CVE-2024-39705",
  "timestamp": "2025-01-14 00:42:31",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:11"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:52"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-13 04:03:30"
    }
  },
  "urls": [
    {
      "url": "https://github.com/nltk/nltk/issues/2522",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/nltk/nltk/issues/3266",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://www.vicarius.io/vsociety/posts/rce-in-python-nltk-cve-2024-39705-39706",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}