{
  "cve_id": "CVE-2024-9287",
  "timestamp": "2025-01-14 00:42:26",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:18"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:47"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-12 23:18:26"
    }
  },
  "urls": [
    {
      "url": "https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/python/cpython/issues/124651",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/python/cpython/pull/124712",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}