{
  "cve_id": "CVE-2023-26151",
  "timestamp": "2025-01-14 16:58:33",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:39:56"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:20"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-12 00:48:59"
    }
  },
  "urls": [
    {
      "url": "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}