{
  "cve_id": "CVE-2024-9979",
  "timestamp": "2025-01-14 00:42:50",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:17"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:56:13"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-13 22:47:52"
    }
  },
  "urls": [
    {
      "url": "https://access.redhat.com/security/cve/CVE-2024-9979",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2318646",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://crates.io/crates/pyo3",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/PyO3/pyo3/pull/4590",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://rustsec.org/advisories/RUSTSEC-2024-0378.html",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}