{
  "cve_id": "CVE-2022-40023",
  "timestamp": "2025-01-14 16:58:31",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-08 10:43:27"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-09 11:54:57"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-08 23:31:49"
    }
  },
  "urls": [
    {
      "url": "https://github.com/sqlalchemy/mako/blob/c2f392e0be52dc67d1b9770ab8cce6a9c736d547/mako/ext/extract.py#L21",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/sqlalchemy/mako/commit/925760291d6efec64fda6e9dd1fd9cfbd5be068c",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/sqlalchemy/mako/issues/366",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://lists.debian.org/debian-lts-announce/2022/09/msg00026.html",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://pyup.io/vulnerabilities/CVE-2022-40023/50870/",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}