```
{
  "vulnerability": {
    "root_cause": "The vulnerability is due to an unspecified flaw in the MySQL Connector/J JDBC driver.",
    "weaknesses": [
      "Unspecified flaw in MySQL Connector/J"
    ],
    "impact": "An attacker with network access can perform unauthorized partial denial of service.",
    "attack_vectors": [
      "Network access"
    ],
    "required_capabilities": "A high-privileged attacker needs network access to exploit the vulnerability."
  },
  "affected_products": [
    "MySQL Connector/J"
  ],
  "references": [
    "https://nvd.nist.gov/vuln/detail/CVE-2020-2933",
    "https://security.gentoo.org/glsa/202105-27",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4QDR2WOUETBT76WAO5NNCCXSAM3AGG3D/",
    "https://lists.debian.org/debian-lts-announce/2020/06/msg00015.html",
    "https://www.debian.org/security/2020/dsa-4703",
    "https://www.oracle.com/security-alerts/cpuapr2020.html",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MDKQVPFT4Z4SFPBH6YNFMJOXKS2YYKHA/"
  ]
}
```